### PR TITLE
Find content-type correctly.

### PR DESCRIPTION
**Pull request by shihshen**
Find content-type based on Name and Value properties under response.Headers since ContentType is always null.

### CODE REVIEW

**Comment by shihshen** [comment]
This PR will help users to get more meaningful response from RWS.

**Comment by mattkoch614** [comment]
This section of code will only be executed in cases where the response returns an HTTP 403 (Forbidden) _and_ we want to take a look at the underlying ODM XML document for some more information, which is when we check if the ``Content-Type`` is ``xml``. 

Some quick tests indicate that the ``IRestResponse`` object that holds the response after performing a ``SendRequest()`` method call does in fact have a collection of Header ``Parameter`` objects, but they are all name/value pairs - indeed, the ``ContentType`` property always seems to be ``null``.

I'm having trouble writing an easily reproducible test for this in the test suite, since the ``SendRequest`` method is a bit verbose and not easily mocked. That being said, at the time of this writing this change doesn't break any other existing tests, so therefore I think we can merge it in. Thanks for the contribution!

**Comment by shihshen** [comment]
I agreed it would be nice to have some unit tests for it. But like you said, mocking is not easy to do now. Having integration tests which actually hit RWS would be ideal. It seems Medidata provide a free test enviroment (https://www.mdsol.com/en/developer-central) which may be useful to run integration tests.
Thank you for this handy library.

**Comment by shihshen** [comment]
May I also know when is this fix going to be released?

**Comment by mattkoch614** [comment]
@powpowshen - This has been merged into master. The associated Nuget package was updated today:
https://www.nuget.org/packages/Medidata.RWS.NET/

**Comment by shihshen** [comment]
Awesome!

**Pull request merged**
